version: 1.0.{build}
branches:
  only:
    - develop
image: Visual Studio 2019
configuration: Release
platform: x64
build:
  verbosity: minimal
artifacts:
- path: '\$(platform)\$(configuration)\exec_in_usersession.exe'
  name: deliverable
notifications:
- provider: Slack
  incoming_webhook:
    secure: /Nbn13tBKGnjqCUJVO23s/Ai7dpGeHVJkahIa/QwlYD0wJEorLtSAJkD1c6WTs+6NKXb6ZRThiH87RUoTdAaQtbkmRTldtIaWp0ArZGVzjE=
  channel: exec_in_usersession
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
