version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
platform: x64
build:
  verbosity: minimal
test_script:
- cmd: vstest.console /logger:Appveyor "C:\projects\exec-in-usersession\x64\Release\UnitTest1.dll"
artifacts:
- path: '\$(platform)\$(configuration)\exec_in_usersession.exe'
  name: deliverable
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: /mCBzuiJFESjib/dzOYgXvhBtl99iGaO8lVO9T03Vln6CquLX9dCfck21Ut6X7Il
  artifact: deliverable
  prerelease: true
  force_update: true
notifications:
- provider: Slack
  incoming_webhook:
    secure: /Nbn13tBKGnjqCUJVO23s/Ai7dpGeHVJkahIa/QwlYD0wJEorLtSAJkD1c6WTs+6NKXb6ZRThiH87RUoTdAaQtbkmRTldtIaWp0ArZGVzjE=
  channel: exec_in_usersession
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
