version: 1.0.{build}
skip_tags: true
branches:
  only:
    - develop
    - master
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: C:\projects\exec-in-usersession
build:
  verbosity: minimal
test_script:
- cmd: vstest.console /logger:Appveyor "C:\projects\exec-in-usersession\x64\Release\UnitTest1.dll"
artifacts:
- path: '\$(platform)\$(configuration)\exec_in_usersession.exe'
  name: deliverable
notifications:
- provider: Slack
  incoming_webhook:
    secure: FrUpuB6Q/TbhMR6ljyV9piIQl7+VnpaR5NbwomaG9iTGG/gyi4S4CHSRfoYHmS51JzA5HlvJKj5C49PU0oCrgrgnTfvKOUKTh0Dxd6WKgdY=
  channel: exec_in_usersession
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
