version: 1.0.{build}
branches:
  only:
    - master
image: Visual Studio 2019
configuration: Release
platform: x64
build:
  verbosity: minimal
artifacts:
- path: '\x64\Release\exec_in_usersession.exe'
  name: deliverable
notifications:
- provider: Slack
  incoming_webhook:
    secure: /Nbn13tBKGnjqCUJVO23s/Ai7dpGeHVJkahIa/QwlYBrO8Ps9I2exOjlCxjIb+ouSj0oNwNHSdJcwLKezLAOpbqVlxVG+WcdhvnrlA8VF+8=
  channel: exec_in_usersession
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
